version: '3.9'

services:
  node-latest:
    image: node:latest
    working_dir: /app
    container_name: node-wp-tracking-conscent
    volumes:
      - ./:/app/
    command: tail -f /dev/null
    ports:
      - '5173:5173'
    networks:
      - node-laboratory

networks:
  node-laboratory:
